name: nizvpn
description: Simple VPN using Platform Channel
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  pull_to_refresh:
    git:
      url: https://github.com/peng8350/flutter_pulltorefresh.git
      ref: nullsafety
  admob_flutter: ^2.0.0-nullsafety.1
  cached_network_image: ^3.0.0-nullsafety
  collection: ^1.15.0-nullsafety.4
  device_apps: ^2.0.1
  device_info: ^2.0.0
  dio: ^4.0.0-prev3
  easy_localization: ^3.0.0
  flutter_inapp_purchase: ^5.0.0
  google_fonts: ^2.0.0
  # google_mobile_ads: ^0.12.1+1
  in_app_review: ^2.0.1
  in_app_update: ^2.0.0
  introduction_screen: ^2.1.0
  dots_indicator: ^2.0.0
  line_icons: ^2.0.1
  lottie: ^1.0.1
  ndialog: ^4.0.1
  package_info: ^2.0.0
  provider: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  snapping_sheet: ^3.1.0
  flutter_native_splash: ^1.3.1

flutter_native_splash:
  background_image: assets/images/launch_image.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/logo_android.png"
  image_path_ios: "assets/icons/logo_ios.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/"
    - "assets/icons/"
    - "assets/languages/"
    - "assets/animations/"
  fonts:
    - family: NerdVPNIcon
      fonts:
        - asset: assets/fonts/NerdVPNIcon.ttf
